# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

steps:
  - script: 
     echo hello world
    displayName: 'run a one-line script'