# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
 name: azure-vm-agent-pool
  # vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    git clone -b develop https://github.com/surya22ganesh/java-app
  displayName: 'Clone GIT REPO'  

- script: 
    mvn clean install
  displayName: 'download maven dependencies'

- script: 
    mvn clean verify
  displayName: 'build java JAR artifact'
